- alias: 'start Aquario Light'
  trigger:
    platform: time
    at: "17:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.luz_aquario
- alias: 'stop Aquario Light'
  trigger:
    platform: time
    at: "20:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.luz_aquario

- alias: Automatic Theme Change
  id: '1511601488029'
  initial_state: 'on' 
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  condition: []
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            default
          {% else %}
            dark
          {% endif %}