- alias: start Aquario Light
  trigger:
    platform: time
    at: '17:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.luz_aquario
- alias: stop Aquario Light
  trigger:
    platform: time
    at: '20:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.luz_aquario
