- id: 06d639243ca842349c1ba2de4c260d16
  alias: Aquario Light
  trigger:
  - at: '17:00:00'
    platform: time
  - at: '20:00:00'
    platform: time
  action:
  - entity_id: light.luz_aquario
    service: light.toggle
- id: 20d651025e9b420295ef627c2e1c16f7
  alias: Aquecimento Agua
  trigger:
  - at: 06:00:00
    platform: time
  - at: 08:00:00
    platform: time
  - at: '18:00:00'
    platform: time
  - at: '19:00:00'
    platform: time
  action:
  - entity_id: switch.aquecimento_agua
    service: switch.toggle
- id: '1578994958446'
  alias: Warn garage gate Open
  description: ''
  trigger:
  - entity_id: cover.portao_garagem
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: O portao da garagem foi aberto
      title: '*Portao da garagem*'
    service: notify.buttler
- alias: tariff change
  trigger:
  - platform: state
    entity_id: electricity.edp
  action:
  - service: utility_meter.select_tariff
    entity_id: utility_meter.daily_energy
    data_template:
      tariff: '{{ trigger.to_state.state }}'
  - service: utility_meter.select_tariff
    entity_id: utility_meter.monthly_energy
    data_template:
      tariff: '{{ trigger.to_state.state }}'
  id: 02a9eda74d13453b9f0923061c1e8a75
- id: '1579542436595'
  alias: warn portao garagem closed
  description: ''
  trigger:
  - entity_id: cover.portao_garagem
    from: open
    platform: state
    to: closed
  condition: []
  action:
  - data:
      message: O portao da garagem foi fechado
      title: '*Portao da garagem*'
    service: notify.buttler
- id: '1583841493592'
  alias: Notify when hacs needs update
  description: ''
  trigger:
  - entity_id: sensor.hacs
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data:
      message: System HACS needs updating
      title: '*HACS*'
    service: notify.buttler
